### ISSUE TITLE
COPY not possible with quoted filenames (parser error "unexpected WORD" on COPY)

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#102]
IBM sample: https://sourceforge.net/p/gnucobol/discussion/cobol/thread/6f24010e48/9542/80b6/d1df/9dc6/dc6d/01c3/ac08/f68b/attachment/DELCURAA.SQB

~~~
$> gixsql --version
gixpp - the ESQL preprocessor for Gix-IDE/GixSQL
Version: 1.0.18dev2
libgixpp version: 1.0.18dev2

$> gixsql DELCURAA.SQB DELCURAA.cob
/tmp/DELCURAA.SQB:72: error: syntax error, unexpected WORD
~~~

line 72 is the one with the first COPY statement:

```cobol
       DATA DIVISION.
       WORKING-STORAGE SECTION.


           COPY 'SQLENV.CBL'.
           COPY 'SQLCA.CBL'.
```

**Comment by mridoni** [comment]
The problem (bug, actually) is the quoted filename not being handled by the parser, I will have to modify the parser and the copy resolver.

**Comment by GitMensch** [comment]
Just rechecked, still "featured" in 1.0.18 (not sure how much work it would be to fix that).

**Comment by mridoni** [comment]
I don't know when I  will be able to issue a (pre-)release, but this patch - to be applied against v1.0.18 - should fix it.

[issue-102.patch.txt](https://github.com/mridoni/gixsql/files/9546646/issue-102.patch.txt)

**Comment by GitMensch** [comment]
mentioned to be fixed in the released version, so -> closing
