### ISSUE TITLE
`GIXSQLCursorFetchOne` error for invalid data

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#107]
Currently the error is set - just to be unset when all result values are set:

https://github.com/mridoni/gixsql/blob/e28180b92409d56d5c9d312e80522ab0ac269068/runtime/libgixsql/gixsql.cpp#L811-L825

I'm sending a fix as PR in the next seconds.

**Comment by GitMensch** [comment]
BTW: Would there be the option to return more details on the actual error (maybe in SQLERRM and only use "invalid column data" as fallback)?
I _think_ other sql environments provide the source / target parameter count that has wrong data in some of the SQLERRD fields (but I'm not sure), maybe this would additionally be possible, too?

Note: I'm sure that seeing this error is only a side effect of a previous error, still looking... (but that's unrelated to this issue).

**Comment by GitMensch** [comment]
Any idea about improved handling of "invalid column data" errors? Should we move that out to a separate issue?

**Comment by mridoni** [comment]
Continuing in just-opened #109
