### ISSUE TITLE
1.0.18a: parser error on semicolon and error continuation does not work

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#128]
given the following sample: https://sourceforge.net/p/gnucobol/bugs/_discuss/thread/21ee5cd91d/81d1/dfcc/attachment/reportWriter01.cob gixpp fails over several semicolons, the first two are:

```text
EXEC SQL
    DISCONNECT ALL;
END-EXEC
EXEC SQL
    ROLLBACK;
END-EXEC
```

Additional to the error stumbling over the semicolon, the error continuation which is wanted in the `badsql` implementation of the parser did not work (the parser stops at the first error).

**Comment by GitMensch** [comment]
@mridoni Could you please recheck if this is solved already or can be solved "easy"?

**Comment by mridoni** [comment]
Yes, this is already scheduled as one of the issues I want/hope to fix in v1.0.19, I will starting working on it in the very next days

**Comment by mridoni** [comment]
cd23889588f9a3217d33984747e120e62910ad92 should fix this

**Comment by GitMensch** [comment]
mentioned as fixed, so closing
