### ISSUE TITLE
re-align COBOL_TYPE_UNSIGNED_BINARY code to use `switch`

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#136]
I'd have sent in a PR, but I'm not sure about the not-yet-checked-in changes with the dynamic memory changing the related code, so here's the suggestion to change those lines:
https://github.com/mridoni/gixsql/blob/debeeeabb9e740f89a03e325e69553ec5e47149f/runtime/libgixsql/SqlVar.cpp#L281-L316
(and similar) to use `switch (this->length)` instead of nested if/else.

I may send in a PR for that when wanted, too.

**Comment by mridoni** [comment]
This is undergoing a massive overhaul due to #124, so a PR would be probably wasted, but I am scheduling this for v1.0.20
