### ISSUE TITLE
broken compile due to spdlog and fmt versions

### ISSUE THREAD

**Issue by dreamwagon** [mridoni/gixsql#138]
Hello. I am trying to build gixsql for amazon linux 2 and am running into problems. The spdlog and fmt versions in the EPEL repository are too old to use with gix so I had to build them both from source. Unfortunately there are still compilation problems in gixsql related to fmt and spdlog. Can you please suggest a work around for the issue below, or let me know what specific versions of fmt and spdlog are required for the make to succeed? 

~~~
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++17 -DSPDLOG_FMT_EXTERNAL -I../../libgixpp -g -O2 -MT libgixsql_la-Connection.lo -MD -MP -MF .deps/libgixsql_la-Connection.Tpo -c Connection.cpp  -fPIC -DPIC -o .libs/libgixsql_la-Connection.o
~~~
~~~
In file included from /usr/local/include/spdlog/spdlog.h:12:0,
                 from Logger.h:25,
                 from IDbInterface.h:28,
                 from IConnection.h:25,
                 from Connection.h:35,
                 from Connection.cpp:21:
/usr/local/include/spdlog/common.h:181:111: error: ‘basic_runtime’ is not a member of ‘fmt’
           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
                                                                                                               ^~~~~~~~~~~~~
/usr/local/include/spdlog/common.h:181:125: error: template argument 2 is invalid
           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
                                                                                                                             ^~~~
/usr/local/include/spdlog/common.h:181:138: error: expected ‘{’ before ‘>’ token
           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
                                                                                                                                          ^
/usr/local/include/spdlog/common.h: In instantiation of ‘struct spdlog::is_convertible_to_any_format_string<const fmt::v9::basic_string_view<char>&>’:
/usr/local/include/spdlog/logger.h:106:47:   required by substitution of ‘template<class T, typename std::enable_if<(! spdlog::is_convertible_to_any_format_string<const T&>::value), int>::type <anonymous> > void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, const T&) [with T = fmt::v9::basic_string_view<char>; typename std::enable_if<(! spdlog::is_convertible_to_any_format_string<const T&>::value), int>::type <anonymous> = <missing>]’
/usr/local/include/spdlog/logger.h:140:35:   required from here
/usr/local/include/spdlog/common.h:201:129: error: incomplete type ‘spdlog::is_convertible_to_basic_format_string<const fmt::v9::basic_string_view<char>&, char>’ used in nested name specifier
 struct is_convertible_to_any_format_string : std::integral_constant<bool, is_convertible_to_basic_format_string<T, char>::value ||
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                                               is_convertible_to_basic_format_string<T, wchar_t>::value>
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
/usr/local/include/spdlog/common.h:201:129: error: incomplete type ‘spdlog::is_convertible_to_basic_format_string<const fmt::v9::basic_string_view<char>&, wchar_t>’ used in nested name specifier~~~

**Comment by GitMensch** [comment]
That's rally hard to read - can you please edit the post inserting the error message using code fences ~~~ ?

**Comment by GitMensch** [comment]
What do you mean with "they are too old to use"? How did you deduce that? Did you install the libspdlog-dev + libfmt-dev system packages?

**Comment by dreamwagon** [comment]
I added the EPEL repository and installed using yum. When I tried to run make for gixsql there were missing methods in both fmt and spdlog.

**Comment by GitMensch** [comment]
Can you please reproduce that and show the output of compile with the EPEL-provided dev packages?

**Comment by dreamwagon** [comment]
Here is what is installed from EPEL

~~~
======================================================================================================================================
 Package                          Arch                          Version                             Repository                   Size
======================================================================================================================================
Installing:
 fmt-devel                        x86_64                        6.2.1-2.el7                         epel                         87 k
Installing for dependencies:
 fmt                              x86_64                        6.2.1-2.el7                         epel                        109 k


==========================================================================================================================================================
 Package                                 Arch                              Version                                  Repository                       Size
==========================================================================================================================================================
Installing:
 spdlog-devel                            x86_64                            0.10.0-1.el7                             epel                             72 k
~~~

This is the error. This header does not exist in the version supplied.

~~~
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++17 -DSPDLOG_FMT_EXTERNAL -I../../libgixpp -g -O2 -MT libgixsql_la-Connection.lo -MD -MP -MF .deps/libgixsql_la-Connection.Tpo -c Connection.cpp  -fPIC -DPIC -o .libs/libgixsql_la-Connection.o
In file included from IDbInterface.h:28:0,
                 from IConnection.h:25,
                 from Connection.h:35,
                 from Connection.cpp:21:
Logger.h:26:10: fatal error: spdlog/sinks/basic_file_sink.h: No such file or directory
 #include "spdlog/sinks/basic_file_sink.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
~~~

**Comment by GitMensch** [comment]
I see, back then (august 2016!) there was only [simple_file_sink.h](https://github.com/gabime/spdlog/commit/bd759bfca7148a5f93d4161bc61a1878731f6259#diff-d02a68789399d32cfe1794fba1b8edf08fb2176805f907cfce7a447a4740387d)
Its version [1.0](https://github.com/gabime/spdlog/releases/tag/v1.0.0) brought that breaking change (also upgrade fmt dependency to 5.1, so this 6.2 is likely fine).

RHEL7 ships the same outdated version, it seems this is more or less the same rpm repo.
RHEL8 ships 1.5.0.

spdlog is commonly installed with the .pc file, so I'lll add a PR that inserts that into configure.ac checking for its availability and also minimal version - as soon as @mridoni specifies which version we need.

How did you come to the conclusion that the fmt-devel package is too old? Which version of spdlog and fmt did you installed from source?

**Comment by dreamwagon** [comment]
Thank your for the response. I arbitrarily picked spdlog-1.7.0 and built from source and got past this issue.

I am getting this error at the end now.

~~~
/usr/bin/ld: //usr/local/lib64/libspdlog.a(fmt.cpp.o): relocation R_X86_64_32S against symbol `_ZTVN3fmt2v612format_errorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
~~~

**Comment by mridoni** [comment]
Hello, sorry, just saw this. spdlog and fmt re a bit of a moving target even in thei most recent versions: there are various `#ifdef`s here and there to account for the differences between the various versions shipped with Debian and or Ubuntu. Nothing dramatic, actually, but a workaround is sometimes required.

If you confirm you can build with the compiler version change I will close the issue.

**Comment by mridoni** [comment]
I have reproduced and tested this on an EC2 instance of Amazon Linux 2, so I am detailing the steps I used below and closing the issue.

First of all: I have used a **t2.medium**-sized instance on AWS for the test: with the standard 4 GBs provided, it choked when trying to compile fmt, I had to add a 4 GB swap file. These are the steps needed to perform the build (for the sake of clarity I have removed many of the `cd <something>`  to enter and exit the build directories.

 
First install some needed packages:
`sudo yum install bison flex mariadb-devel unixODBC-devel postgresql-devel fmt-devel spdlog-devel automake autoconf pkgconfig cmake3 git`

Then [follow the procedure here](https://stackoverflow.com/questions/61165009/how-to-install-devtoolset-8-gcc-8-on-amazon-linux-2) to add GCC 8 (Amazon Linux 2 is a derivative of RHEL7, that comes with GCC 4.8.5, way too old for our needs).

Build v1.10 of spdlog:
```
wget https://github.com/gabime/spdlog/archive/refs/tags/v1.10.0.tar.gz
tar -xzvf 1.10.0.tar.gz
cd spdlog-1.10.0/
mkdir build && cd build
cmake3 .. && make -j
sudo make install
```

Build v9.1.0 of fmt:
```
wget https://github.com/fmtlib/fmt/archive/refs/tags/9.1.0.tar.gz
tar -xzvf 9.1.0.tar.gz
cd fmt-9.1.0/
mkdir build && cd build
cmake3 .. -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE && make -j
sudo make install
```
Here, if you want to use and keep around a shared library version of spdlog, instead of linking to it statically, you can use:
`cmake3 .. -DBUILD_SHARED_LIBS=TRUE && make -j`

Then build GixSQL the usual way:
```
wget https://github.com/mridoni/gixsql/releases/download/v1.0.20/gixsql-1.0.20.tar.gz
tar -xzvf gixsql-1.0.20.tar.gz
cd gixsql-1.0.20
./configure --prefix=/my/install/path
make -j && sudo make install
```
