### ISSUE TITLE
Potential issue with release el8 rpm

### ISSUE THREAD

**Issue by processor286** [mridoni/gixsql#149]
Trying to test a simple program am faced with the following error, here are some details of the software and platform.

gixsql was installed from the distribution RPM using yum

**OS Version**
cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.7 (Ootpa)

**COBOL version**
cobc --version
cobc (GnuCOBOL) 4.0.0
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Keisuke Nishida, Roger While, Ron Norman, Simon Sobisch, Edward Hart
Built     May 19 2023 14:58:32
Packaged  May 19 2023 14:57:59 UTC
C version "8.5.0 20210514 (Red Hat 8.5.0-16.0.2)"

**GIX SQL version**
gixsql --version
gixpp - the ESQL preprocessor for Gix-IDE/GixSQL
Version: 1.0.20b
libgixpp version: 1.0.20b

**installed RPM**
rpm -qa | grep gix
gixsql-1.0.20b-1.el8.x86_64

**Compilation and link attempt**
cobc -x T2.cbl -lgixsql
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libgixsql.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
****

I've probably done something silly here, but appreciate a pointer in the right direction :)

**Comment by processor286** [comment]
I might add, I've seen posts about filesystem in C++ and suggesting adding -lstdc++fs  but this doesn't help, I don't have that library installed anywhere, and 'yum' did not bring in a dependency for it when I did:

yum -y install https://github.com/mridoni/gixsql/releases/download/v1.0.20b/gixsql-1.0.20b-1.el8.x86_64.rpm

**Comment by GitMensch** [comment]
This may be kind of a duplicate to #18; along with a _possible_ broken el8 rpm.

Also see the note in the README about that: https://github.com/mridoni/gixsql/blob/fe866af4c648da9f79c457b6b2e5f977f5e12c1d/README.md?plain=1#L416

**Comment by GitMensch** [comment]
The important question is how the el8 RPM was built  - and fix the missing dependency in there;
I suggest to edit the issue title to point out that the el8 rpm is not functional

**Comment by mridoni** [comment]
Yes, the workflow is actually a very simple, but I don't have a lot of experience with RPMs/RHEL/etc. so I might easily have missed something. I will try to make more tests during the next week.

**Comment by mridoni** [comment]
I reproduced it, in the next few days I will start working on a fix

**Comment by mridoni** [comment]
I have just uploaded new RHEL/AlmaLinux packages (package version is 1.0.20b-4); these should solve the install/link problems mentioned here.

**Comment by processor286** [comment]
@GitMensch  yes, it is, sorry for delay.

**Comment by GitMensch** [comment]
Please click on close then. Thank you.
