### ISSUE TITLE
Erro in cobc execution: libgixsql.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'

### ISSUE THREAD

**Issue by sergiosa61** [mridoni/gixsql#177]
In trying to compile a cobol program whith cobc for our Oracle migration project, I get the following error.

` /bin/ld: /opt/install/lib/libgixsql.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'`

**The gixpp version**

```
gixpp -V
gixpp - the ESQL preprocessor for Gix-IDE/GixSQL
Version: 1.0.20b
libgixpp version: 1.0.20b
```

**The cobc version**

```
cobc -V
cobc (OpenCOBOL) 2.0.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     Nov 30 2023 11:35:35
Packaged  Feb 11 2012 12:36:31 UTC
C version "8.3.0"
```

**Comment by GitMensch** [comment]
First: if anyhow possible, you really should update to GnuCOBOL (3.2 was released); the "hard" part is that moving from OpenCOBOL to GnuCOBOL will need a recompile (GC 2.2->3.x doesn't need one).

For the error above: I _guess_ you've used the libgixsql binaries, right? What is the output of `cat /etc/*release`?
I _guess_ that's a very old machine (note if it is RHEL7: that goes out of vendor support soon) and to fix that you'll have to recompile libgixsql.

**Comment by sergiosa61** [comment]
Sorry, I solved it by adding the parameter LIBS=-lstdc++fs on configuration command

**Comment by GitMensch** [comment]
Yes, that's also documented in the README https://github.com/mridoni/gixsql/blob/69e26719ecaca2c31bdf91d7add270b1c0ce2286/README.md#building-from-source and https://github.com/mridoni/gixsql/issues/18 "possibly tackles" to do that automatically (checked in the configure script if needed and working)
