### ISSUE TITLE
Gnucobol and esql (with gixp)

### ISSUE THREAD

**Issue by proteomis** [mridoni/gixsql#180]
Hello,
I use gnucobol under WIndows 11, cobc (GnuCOBOL) 3.3-dev.0

I am trying to compile source code using embedded Sql for Cobol and use the gixpp (or gixsql) precompiler to generate source code.

During the precompilation, it seems that the gixpp does not handle copy files in the exec sql begin declare section:
For example :
```
       EXEC SQL BEGIN DECLARE SECTION END-EXEC.
              copy "infos_connexion.cpy".
       EXEC SQL END DECLARE SECTION END-EXEC.
       EXEC SQL INCLUDE SQLCA END-EXEC.

```
where I declare :
```
       01 Svr                    pic x(32) value "xxxxxx".  *> the database
       01 Usr-Pass               pic x(64) value "user.password".
```

in order to use the later in the procedure division :
```
            exec sql
               connect to :Svr as libpar_conn user :Usr-Pass
            end-exec
```

The precompiler generates an error:
```
Invalid or undefined parameter name: Usr-Pass
tstTxtLibpar.cbl(36): error: Error in ESQL statement
```

If Svr and Usr-Pass are declared in the file, it precompiles without error.
Am I doing something wrong or is it a limitation of the precompiler ?

Regards

**Comment by GitMensch** [comment]
`COPY` statements are _expected_ to be handled by the compiler, _after_ `EXEC XYZ` is already processed..

What you likely want is `EXEC SQL INCLUDE "infos_connexion" END-EXEC`.

**Comment by proteomis** [comment]
That is absolutely correct! This syntax is allowed when compiling under MF and I assumed it was the same. I was wrong!
Another issue is that gixpp adds tokens in colums 1 to 6 and comments with a star in column 7. And it can't be compiled using the free format unless modifying that by hand in the source file generated by the precompiler.
IMHO free format is so much more pleasant to use than the very restrictive historical format that it should be the de facto format to use!
Thanks for your help.

**Comment by GitMensch** [comment]
> That is absolutely correct! This syntax is allowed when compiling under MF and I assumed it was the same. I was wrong!

There's no problem in editing the title to something like "FR: Micro Focus ESQL parsing COPY in EXEC SQL DECLARE" and add missing information (what _exactly_ was used before. how _exactly_ was that invoked, ideally with links to documentation).

... but `gixqsql --help` shows something - did you try `--esql-preprocess-copy` already?

Fixed form reference-format seems to be tracked by #40.

**Comment by proteomis** [comment]
>... but gixqsql --help shows something - did you try --esql-preprocess-copy already?

Yes I tried this without success.
Modifying to the `EXEC SQL INCLUDE "infos_connexion" END-EXEC` works.
Thanks for the tip!
Regards.

**Comment by proteomis** [comment]
Thx

**Comment by GitMensch** [comment]
@mridoni It seems there are no test cases for `--esql-preprocess-copy`, could you add one?
