### ISSUE TITLE
error msg trying to install in mingw/msys2 2024.12.04 < extra_files.mk

### ISSUE THREAD

**Issue by jmcnamara10001** [mridoni/gixsql#194]
$ autoreconf --install
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:5: warning: AC_INIT: not a literal: "'1.0.21dev'"
configure.ac:21: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
../autoconf-2.72/lib/autoconf/programs.m4:743: _AC_PROG_LEX is expanded from...
../autoconf-2.72/lib/autoconf/programs.m4:736: AC_PROG_LEX is expanded from...
configure.ac:21: the top level
configure.ac:136: warning: back quotes and double quotes must not be escaped in: invalid DBMS driver id \"${with_default_driver}\".
../autoconf-2.72/lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
../autoconf-2.72/lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:136: the top level
automake-1.16: error: cannot open < extra_files.mk: No such file or directory
autoreconf-2.72: error: automake failed with exit status: 1

Hi Simon/all-

I tried DB2 but either a virus or my norton went crazy so i cant use it. So I am trying Simon's suggestion but am having a little trouble installing. I added all the prerequisites with Pacman -S ... the whole list - any ideas about the msg. ? thanks jim

**Comment by jmcnamara10001** [comment]
hi,
I am realizing i forgot to put windows 11 mingw msys2-x86_64-20241116.exe thanks

**Comment by GitMensch** [comment]
I suggest to use the tar.gz from the release https://github.com/mridoni/gixsql/releases/latest, then

    tar -xvf gix*.gz
    cd gix*
    mkdir build
    cd $_
    ../configure # your options - check --help for them

No need for any autoconf/automake invocation at all.

... and if you cannot build it, then there's always the option to fall back to the installer provided in the release or even an installer providing both GnuCOBOL and GixSQL like the aio from superbol.

**Comment by jmcnamara10001** [comment]
simon, i got it to run and install with both gix and gixsql but it wont launch with parameters. I put ./psql -U usrname -h 127.0.0.1 -p 5432 -d mydb1 -W and i can get in on psql command line but not when i supply the db parameters connections please advise of any tricks if you have a suggestion. i really like this environment. It looks way cool. I even supplied schema public too. I used the supplied connections dialog to fill them in.  thanks jim

**Comment by jmcnamara10001** [comment]
i just wanted to add my dsn capability is cripple-ware i couldnt set up a dsn through this version of windows in my windows settings so i am relying on pgsql driver but i thought that would be covered in the ./psql set up that comes with mingw requirement for install through pacman. please advise. thanks

**Comment by jmcnamara10001** [comment]
simon- i found out that the base directory and i dont know about that isnt set up so i am going to install the compiler in a separate location. sorry, jim

**Comment by jmcnamara10001** [comment]
one last comment i put in the postgresql 17.2 odbc driver from postgres edb but it is not connecting yet.. i tried some samples on your screen but my postgresql is for mingw i dont know if that makes a difference thanks, jim

**Comment by jmcnamara10001** [comment]
"c:\msys64\mingw64\bin\cobc" -x TEST001.cbsql -L "C:\msys64\home\stealth_droid\gixsql-binaries-windows-x64-mingw\lib\x86\gcc" -lgixsql
configuration error:
/mingw64/share/gnucobol/config\default.conf: No such file or directory
oh and one more i tried in the path C:\Users\stealth_droid\Documents\Gix\Examples\test001\bin\debug\x64 to run it manually but got an error after setting the 2 environment variables  set DBNAME=pgsql://127.0.0.1:5432/mydb1
  set DBAUTH=test001.test001 so i don't know i through almost the kitchen sink at this one... thanks for any input...

**Comment by jmcnamara10001** [comment]
Yes, you can move the default.conf file to the same directory as cobc, and it should work as long as cobc is able to find the configuration file in that directory.

However, the key is ensuring that cobc is looking in the right location for the configuration file. By default, cobc may look for default.conf in a specific directory like /mingw64/share/gnucobol/config/. If you move default.conf to the same directory as cobc, you need to ensure that cobc knows where to find it. 
so my question is as to why it is looking slightly off the beaten path or why am i slightly off the beaten path thanks <above from chatgpt> jim

**Comment by jmcnamara10001** [comment]
hi simon, i looked and looked and looked and found this 
 IDENTIFICATION DIVISION.
       PROGRAM-ID. PGMAIN.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
        01 TABLE-VARS.
           05 VDEPT-NO PIC X(4).
           05 VDEPT_NAME PIC X(40).
        01 DB-PRE-VARS.
           05 DATASRC PIC X(100) VALUE 
               "mysql://localhost:3306/employees".
           05 DBUSR pic x(4) value "root".
           05 DBPSW pic x(4) value "sqlp".

I couldnt figure out where to put the DATASRC and how to do it because the dialog for connection parameters didnt seem to do it for me. so now seeing this i hope to have better luck thanks jim

**Comment by jmcnamara10001** [comment]
It seems like the issue persists with the path format, specifically with the COB_CONFIG_DIR environment variable still being set incorrectly. The error message suggests that cobc is unable to find the configuration file default.conf because the path is being interpreted as C:\msys64\share\gnucobol\config instead of the Unix-style path /mingw64/share/gnucobol/config.

Issue Recap:
The path format: The COB_CONFIG_DIR is expected to be in Unix-style (/mingw64/share/gnucobol/config), but it is still being treated as a Windows-style path (C:\msys64\share\gnucobol\config).
The setx command: It doesn't handle Unix-style paths properly, leading to incorrect path assignments in the environment.
Plan:
Avoid using setx: As mentioned earlier, setx is not suitable for setting Unix-style paths. MSYS2 requires environment variables to be set using export in shell configuration files like .bashrc.
Use cygpath correctly to ensure the conversion of the path format works as expected.
Fix:
To directly address this, we will ensure the path is converted properly and set the environment variable for the current session. This avoids using setx for MSYS2 and uses the correct Unix path format.

Solution:
Manually set the COB_CONFIG_DIR using cygpath in the MSYS2 shell and avoid the setx command.
Ensure the ~/.bashrc file contains the proper export statement for future sessions.
Step-by-Step Solution:
Step 1: Set the Environment Variable for the Current Session
Instead of using setx (which is for Windows), we can use the export command directly in the MSYS2 shell to set the environment variable.

Run this in your MSYS2 shell (or place it in your .bashrc):

bash
Copy code
export COB_CONFIG_DIR=$(cygpath -u "C:\msys64\share\gnucobol\config")
This will convert the Windows path to a Unix-style path and set COB_CONFIG_DIR for the current session.

Step 2: Update ~/.bashrc for Future Sessions
To ensure that COB_CONFIG_DIR is set correctly for future sessions, we need to modify your ~/.bashrc file. You can manually edit the file or append the following line to it:

bash
Copy code
echo 'export COB_CONFIG_DIR=$(cygpath -u "C:\msys64\share\gnucobol\config")' >> ~/.bashrc
This will ensure that every time you start a new MSYS2 shell, the COB_CONFIG_DIR variable will be set correctly.

Step 3: Test the Environment Variable
Source the ~/.bashrc or restart the MSYS2 shell to load the new configuration:

bash
Copy code
source ~/.bashrc
Check the environment variable:

bash
Copy code
echo $COB_CONFIG_DIR
This should return:

bash
Copy code
/mingw64/share/gnucobol/config
Step 4: Re-run the cobc Command
Now, try running the cobc command again to see if it works:

bash
Copy code
/mingw64/bin/cobc -c TEST1001.cbl
Explanation:
Using cygpath: The cygpath -u command converts the Windows path (C:\msys64\share\gnucobol\config) into a Unix-style path (/mingw64/share/gnucobol/config).
Using export: This command sets the environment variable for the current shell session, ensuring that MSYS2 tools can find the configuration directory.
~/.bashrc: This is where environment variables should be stored for persistent changes in MSYS2, so adding the export command here ensures that it will be set each time you start a new shell.
Conclusion:
By setting the environment variable COB_CONFIG_DIR using export with cygpath, you ensure that the path is converted correctly for MSYS2 tools, and they will be able to find the default.conf configuration file. This should resolve the error you were encountering. Let me know if this works or if you encounter further issues!


THE CHATGPT TOLD ME HOW TO GET PAST USING THE COMMAND LINE WHERE I RAN INT O THE ERROR MESSAGE 
configuration error:
/mingw64/share/gnucobol/config\default.conf: No such file or directory

SO NOW I CAN FOCUS ON HOW TO GET THIS THING TO COMPILE MAYBE ON THE COMMAND LINE AND PREPROCESS AND THEN WORRY ABOUT THE IDE. OR SOME SUCH. I HAVE A LOT OF WORK TO DO. SORRY. THANKS. JIM
