### ISSUE TITLE
gixpp syntax error unexpected end of file mingw

### ISSUE THREAD

**Issue by jmcnamara10001** [mridoni/gixsql#195]
Hi all-

does anyone ever get this error?

here is my syntax i fed to it...
gixpp -e -S -I --esql-copy-exts=".,*.cpy,*.CPY" -i TEST001.cbl -o TEST001.cbsql
TEST001.cbl(21): error: Wrong file format or unexpected end of file
C:\Users\stealth_droid\Documents\Gix\Examples\test001\bin\debug\x64\TEST001.cbl(21): error: syntax error, unexpected end of file
thanks,
jim

**Comment by GitMensch** [comment]
Maybe an open EXEC SQL (in this case the error handling should be improved)?

Never harms to finish the source with a line break.

**Comment by jmcnamara10001** [comment]
Hi Simon,

I learned another 'trick' AKA something I shouldn't be doing...

I can't run cobc -x TEST001.cbl first and then gixpp.

I need to run gixpp and then cobc -x TEST001.cbl 

or some such...

otherwise the error message wrong file format or unexpected end of file

thanks, 
jiim
