### ISSUE TITLE
git has viruses 'according to virus total' where can i please get a copy

### ISSUE THREAD

**Issue by jmcnamara10001** [mridoni/gixsql#197]
Hi-

I am trying to get gix so i can use gixcc to compile my project after running it through gixpp and gixsql.

I am getting a little better at detecting things and fixing things as i go but i am still a very much wip.

Please assist where i can get a virus free copy of gix so i can use gixcpp like this...
gixcc TEST001.o -o TEST001.exe -L"C:\msys64\mingw64\lib" -lgcc -lgnucobol

The link from the files that gave me the virus is from here..
https://github.com/mridoni/gix
i think ... but please help me verify.

thanks,
jim

**Comment by jmcnamara10001** [comment]
i was looking in particular for the folder with the gix.tar.gz thanks

**Comment by GitMensch** [comment]
The virus note is a false-positive (I suggest to upload the installer and reported exe to virustotal.com to get a better picture)...
but in any case, if you just use gixsql (or instead of the wrapper the matching gixpp command), then it is enough to directly use `cobc` afterwards - no need for any additional link  options either.

[with a MSYS2 build - on msys2 use cobenv.sh to do the setup, otherwise cobenv.cmd, no manual tinkering with any environment variables needed]

**Comment by jmcnamara10001** [comment]
PLEASE SEE CLOSING REASON LISTED HERE.  I GOT ATTACKED BY VIRUSES. IT HAS TO BE THE REASON WHY THINGS ARENT WORKING https://github.com/mridoni/gixsql/issues/198

**Comment by GitMensch** [comment]
Norton is one of the kings for false-positive... If on virustotal only one to three vendors yield a result, especially if it is a "generic'" or "heuristic" one, I wouldn't give much weight to it, if it is from a trusted source.

**Comment by jmcnamara10001** [comment]
Thanks Simon.

I switched to spectrum f-secure for the scanner and try to use Norton for the firewall.
If that doesn't work I will just go with f-secure/spectrum for the whole security suite thing.

I'll have to whitelist something on each. Maybe I can do that tonight while I am waiting for Norton to let me know that it is 'not malware'.

Thanks for the guidelines on 1 to 3 and generic or heuristic with trusted source.

Hopefully in the next day or so I can be out from under these attacks on my pc from false positives if that is what it is because i can't get a darn thing done otherwise.

Have the coolest Christmas/holiday,
jim

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
