### ISSUE TITLE
not very friendly - weird error messages - postgresql 

### ISSUE THREAD

**Issue by jmcnamara10001** [mridoni/gixsql#198]
Hi -

I get the weirdest error messages when using gixsql.
Also, the cursors for postgresql fetch for displaying
records don't like to work.

I wish we had more code that demonstrated autocommit = off
and autocommit=on and native versus non-native cursor
handling for postgresql.

I vote minus 1 for postgresql right now! Is something else better
supported than postgresql possibly? Desperate to find a db
that works with this. thanks

please correct me if you are actually using it and it is working.
I'd be happy to be wrong for the greater good.
Please verify that you are using the same version which is 
version 1.02.0b

Please UPVOTE if you are using this and it is working. I need
to know if it is just me that is having these issues.

thanks

$ cobc -x t001.cbsql
t001.cbsql: in paragraph 'GIXSQL-CI-P-t001-CRSR-TAB00':
t001.cbsql:415: error: syntax error, unexpected Identifier
  413 | GIXSQL         BY VALUE 0
  414 | GIXSQL     END-CALL
  415 > GIXSQL GIX-SKIP-CRSR-INIT.
  416 | GIXSQL*
  417 | GIXSQL*   ESQL CURSOR DECLARATIONS (END)
t001.cbsql: in paragraph '999-PRG-ERR':
t001.cbsql:404: error: 'GIX-SKIP-CRSR-INIT' is not defined
  402 | GIXSQL*
  403 | GIXSQL*   ESQL CURSOR DECLARATIONS (START)
  404 > GIXSQL     GO TO GIX-SKIP-CRSR-INIT.
  405 | GIXSQL GIXSQL-CI-P-t001-CRSR-TAB00.
  406 | GIXSQL     CALL STATIC "GIXSQLCursorDeclare" USING

sorry for negative feedback. i wish i had better luck,
jim

**Comment by jmcnamara10001** [comment]
Hi -

I just sent a file to norton ldd to ask if it is malware. it says idp.generic and got quarantined. i asked chatgpt if i need that to link and it said yes it is somehow related with a wrapper ld to ldd. so i think it is impacting my .EXE results possibly. i will find out if it is a virus once and for all and maybe i wont get gobbly gook if i can get it off my system of fix it. THANKS

**Comment by GitMensch** [comment]
The output above is from cobc (possibly not a current version) that says something is amiss, looks like you have placed an `EXEC SQL` before a paragraph `GIX-SKIP-CRSR-INIT` and not ending it with a period, which is necessary before starting any new procedure - but as the original code is missing we can't know for sure.
