### ISSUE TITLE
FR: add parsing for "SELECT without INTO"

### ISSUE THREAD

**Issue by mridoni** [mridoni/gixsql#2]
Concerning "SELECT without INTO": rechecking on my side shows that the additional `INTO :RESINT` was used in the ocesql environment, too. The one without it was preprocessed by citpgsql.
It is possibly reasonable to add parsing for that, while it commonly won't be that useful; maybe with a warning?

_Originally posted by @GitMensch in mridoni/gixsql#3

**Comment by GitMensch** [comment]
Ping on possibly adding either that syntax in gixsql or a helpwanted label to this issue if it awaits a PR.

**Comment by mridoni** [comment]
Fixed in the internal repository, all tests pass with no regressions, will be in v1.0.18
