### ISSUE TITLE
release tarball missing

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#35]
Please publish a release tarball. This should be created by `make dist` (running `make distcheck` to test for its general usability from time to time is a good thing in general).

A release tarball will contain all necessary files with correct timestamps, the auto-available GitHub "asset" has timestamps that will trigger a recreation of some files needing "maintainer-only" tools (automake, autoconf, bison, flex, possibly more).

Can we hope for a new release that includes a fix for #1 and #8 "soon"?

**Comment by mridoni** [comment]
> Please publish a release tarball. This should be created by `make dist` (running `make distcheck` to test for its general usability from time to time is a good thing in general).
> 
> A release tarball will contain all necessary files with correct timestamps, the auto-available GitHub "asset" has timestamps that will trigger a recreation of some files needing "maintainer-only" tools (automake, autoconf, bison, flex, possibly more).

Ok, noted.

> Can we hope for a new release that includes a fix for #1 and #8 "soon"?

I will try to work on this starting from the next weekend or so, as usual it depends on my day-job.

**Comment by mridoni** [comment]
Fixed in [v1.0.15](https://github.com/mridoni/gixsql/releases/tag/v1.0.15)
