### ISSUE TITLE
32bit binaries (at least win32) in the releases

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#41]
Back with GixSQL there were packages for this; could they also be part of a release here?

**Comment by mridoni** [comment]
Yes, and they will. I have been publishing single source fixes to speed up development, since building and checking all the packages for each change slows down the release process, but I will definitely publish a new release (v1.0.15, I guess) as soon as I have fixed a few issues that can be fixed in a resonable timeframe.

**Comment by GitMensch** [comment]
Totally reasonable.

The main point of this issue was, that - so far - only 64bit binaries were published in this repo.

To ease the release process makefiles/scripts to do the binarie creation are important, the second important thing is to add automated testing.
If both is done (easier here than with the ide), then the release process can be automated: then just tag and the CI will build, then test and if all tests pass so the release with all binaries (and if course dist tarball) attached.

**Comment by mridoni** [comment]
> The main point of this issue was, that - so far - only 64bit binaries were published in this repo.

Yes, I realized that just after I posted my comment. Not a problem, the Windows 32 bit package is easy to add.

> To ease the release process makefiles/scripts to do the binarie creation are important, the second important thing is to add automated testing. If both is done (easier here than with the ide), then the release process can be automated: then just tag and the CI will build, then test and if all tests pass so the release with all binaries (and if course dist tarball) attached.

Yes, that's the direction I will probably be taking in due time, at least for GixSQL (Gix-IDE has a series of packaging and testing requirements that make using GitHub actions unfeasible or at least too complicated to be actually useful). The only problem I see is that, last time I checked, GitHub actions didn't properly support building C++ projects with MSBuild (CMake only was available) but that might have changed with the release of Visual Studio 2022.

**Comment by GitMensch** [comment]
> last time I checked, GitHub actions didn't properly support building C++ projects with MSBuild

I haven't done this myself but that should be easy to do - just check the "marketplace" for actions then adjust them as needed, in your case that seems like https://github.com/marketplace?type=actions&query=msbuild

**Comment by mridoni** [comment]
I have already set up the modified build scripts for gixsql x86 packages on Windows, I need to check the generated packages, that will be part of the pre-release testing phase for v1.0.15.
