### ISSUE TITLE
DISCONNECT is broken

### ISSUE THREAD

**Issue by mridoni** [mridoni/gixsql#72]
`EXEC SQL DISCONNECT` does not work as it should, and at all with named connections.

**Comment by GitMensch** [comment]
Just dropping it here as it came up with ESQL once and would be a good thing to add to the testsuite:  `DISCONNECT ALL` - is that  already expected to be working? If not I suggest to reference this in a new issue :-)
Would it be handled in the driver (= all open connections stored, then closed at once) or by the underlying library?

**Comment by mridoni** [comment]
No, it’s not implemented yet, but it should be quite easy. Can you reference your comment in a new issue?

Thanks
