### ISSUE TITLE
gixsql: long queries break COBOL compiler

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#8]
Different dialects have different literal lengths.
The default of GnuCOBOL is 8191 characters (per COBOL 2014).

COBOL 2002 still has the limit of COBOL85: 160 characters - and IBM Enterprise COBOL for z/OS 6.3 also still has that limit.
MicroFocus COBOL seems to be at 8192, ACUCOBOL-GT at 4096.

The most portable way to define the query definitions would therefore not be:

```cobol
01  SQ0021.
    02  FILLER PIC X(%d) VALUE "..."
 &  "..."
[...]
 &  "...".
 ```
 
 but using chunks of 160 characters max.:
 
 ```cobol
01  SQ0021.
    02  FILLER PIC X(160) VALUE "..."
 &  "..."
 &  "...".
[...]
    02  FILLER PIC X(160) VALUE "..."
 &  "..."
 &  "...".
    02  FILLER PIC X(%d) VALUE "..."
 &  "..."
 &  "...".
 ```

But then there's also the issue of some compilers not supporting string concatenation with `&` or `"..."-` either.

Maybe it is useful to add a flag "cobol85" or similar which uses chunks of 160 bytes and continuation lines instead of `".." & "."` and otherwise go with 8191 chunks and `&` concatenation?

I've already found the code to handle this in `TPESQLProcessing::put_query_defs`, looks like it primarily needs another loop in it.
 
 Note: ocesql writes chunks of 256 max `FILLER` entries (in a really ugly way).
 ... and yes, I have more than 1 program with a bigger query (even when I question the use of it...).

**Comment by GitMensch** [comment]
> there's a COBOL85 option which (now likely correctly) can work around this

Nope, the values are still broken:

~~~
GIXSQL 01  SQ0001.
GIXSQL  02  FILLER PIC X(51) VALUE "SELECT SOMEOEWID FROM TAB WHERE HI
GIXSQL-    "STID = $1 LIMIT 1".
GIXSQL 01  SQ0002.
GIXSQL  02  FILLER PIC X(165) VALUE "SELECT SOMEOEWID FROM TAB WHERE HI
GIXSQL-    "STID = (SELECT MAX(HISTID) FROM ATTH WHERE SNR_TN = $1 AND
GIXSQL-    "SNR = $2 AND MNOTAB = $3 AND MNO = $4 AND TRANSID <= $5 AND
GIXSQL-    " TRANSID > 0)".
~~~

* the size number number should likely always use three characters --> "051" instead of "51" to have same place where "VALUE" starts [the first sample has a size too big by 2]
* the "data" should be written to column 72 including, currently it goes _until_ column 72 so every line has an additional space and the full statement is then trimmed on the end

**Comment by mridoni** [comment]
Ok, noted

**Comment by GitMensch** [comment]
Is it expected for this issue to be solved soon?
It is "just" about:

* for standard mode: add one sister-FILLER for long fields and split by 4096 or 8191.
* cobol85 mode: get the start/end positions correct [I guess that's just a minor adjustment]

**Comment by mridoni** [comment]
Yes, it’s the next item on my list. If all goes well I will probably release the last modifications as 1.0.15
