### ISSUE TITLE
Have `USE_VARLEN_32` be the default as long as there's a fixed varlen

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#80]
> So I do wonder: Shouldn't `USE_VARLEN_32` be the default as long as there's a fixed varlen only?

Yes, that's probably for the better, I'll add this to the next batch of fixes.

_Originally posted by @mridoni in https://github.com/mridoni/gixsql/issues/54#issuecomment-1134315663_

... just found out: that default wasn't changed in GixSQL 1.0.16 yet, please do so for upcoming release.

**Comment by mridoni** [comment]
You are right, I forgot, thanks for pointing it out.

**Comment by mridoni** [comment]
Changed in the internal repository to use 32 bit indicators as the default. 16-bit indicators are available when defining `USE_VARLEN_16` (`USE_VARLEN_32` is not in use anymore).

**Comment by mridoni** [comment]
This change (luckily) exposed a few bugs that have been caught during the regression tests and are currently being fixed.

**Comment by GitMensch** [comment]
fixed (per release notes)
