### ISSUE TITLE
CURSOR for prepared statements don't compile

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#81]
Code originally written for ocesql:

```cobol
           MOVE 'SELECT MAX(VAR) FROM TAB' TO SQLCOMMAND-ARR
           MOVE FUNCTION LENGTH (FUNCTION TRIM (SQLCOMMAND-ARR))
             TO SQLCOMMAND-LEN
          *> line 223 follows
           EXEC SQL AT :DBS
               PREPARE S1 FROM :SQLCOMMAND
           END-EXEC.
          *> line 231 follows
           EXEC SQL AT :DBS
               DECLARE VARMAX CURSOR FOR S1
           END-EXEC.
          *> line 239 follows
           EXEC SQL AT :DBS
               OPEN VARMAX 
           END-EXEC.
          *> line 247 follows
           EXEC SQL AT :DBS
               FETCH VARMAX 
               INTO
                 :VAR-MAX
           END-EXEC.
          *> line 259 follows
           EXEC SQL AT :DBS
               CLOSE VARMAX 
           END-EXEC.
```

currently resulting in

> TEST.pco:232: error: syntax error, unexpected TOKEN, expecting SELECT
> TEST.pco:240: warning: AT DB-NAME is not allowed for CURSOR access, always used from CURSOR DECLARE
> TEST.pco:248: warning: AT DB-NAME is not allowed for CURSOR access, always used from CURSOR DECLARE
> TEST.pco260: warning: AT DB-NAME is not allowed for CURSOR access, always used from CURSOR DECLARE

Line 223 is expected to compile what it does, but not to work yet; but that's tracked as #79 and "solved in internal repo".
The warnings in line 240,248,260 are totally correct - but why is there an error for line 232?

**Comment by mridoni** [comment]
Declaring a cursor from a prepared statement is currently not supported. I guess ocesql does something behind the scenes, since PostgreSQL does not support it natively: according to the documentation you can only have a full-blown query (or a `VALUES` clause) as the source for a `DECLARE CURSOR` statement.

I am flagging this as an enhancement, it shouldn't be too difficult to implement (at least in the PostgreSQL driver).

**Comment by mridoni** [comment]
The following code compiles and runs correctly. Basically you can declare a cursor in three different ways:

- "direct" statement (the usual way)
- passing the name of a prepared statement as an identifier
- passing a variable reference

In all three cases the content of the actual query is evaluated at runtime, when the cursor is open (not during the declare phase).

For now this works only for cursors declared in the WORKING-STORAGE SECTION, I just need to fix the generated calls in the preprocessor and run the usual non-regression tests.

       IDENTIFICATION DIVISION.
       
       PROGRAM-ID. TSQL026A. 
       
       
       ENVIRONMENT DIVISION. 
       
       CONFIGURATION SECTION. 
       SOURCE-COMPUTER. IBM-AT. 
       OBJECT-COMPUTER. IBM-AT. 
       
       INPUT-OUTPUT SECTION. 
       FILE-CONTROL. 
       
       DATA DIVISION.  

       FILE SECTION.
      
       WORKING-STORAGE SECTION. 
       
           01 DATASRC     PIC X(64).
           01 DBUSR       PIC X(64).
           01 DBPWD       PIC X(64).
           01 DBS         PIC X(64).

           01  SQLCOMMAND.
               49 SQLCOMMAND-LEN    PIC S9(4) COMP-5.
               49 SQLCOMMAND-ARR    PIC X(250).

           01 IDX         PIC 9(8).
           01 VAR-TMP     PIC 9(8).
           01 VAR-RES     PIC 9(8).
           
           01 CUR-STEP    PIC X(16).
               
       EXEC SQL 
            INCLUDE SQLCA 
       END-EXEC. 

       EXEC SQL AT :DBS
           DECLARE VM1 CURSOR FOR :SQLCOMMAND
       END-EXEC.
      
       EXEC SQL AT :DBS
           DECLARE VM2 CURSOR FOR PREPSTMT1
       END-EXEC.
      
       EXEC SQL AT :DBS
           DECLARE VM3 CURSOR FOR 
                SELECT MAX(VAR) - MIN(VAR) FROM TAB00
       END-EXEC.

       PROCEDURE DIVISION. 
 
       000-CONNECT.
           DISPLAY "DATASRC" UPON ENVIRONMENT-NAME.
           ACCEPT DATASRC FROM ENVIRONMENT-VALUE.
           DISPLAY "DATASRC_USR" UPON ENVIRONMENT-NAME.
           ACCEPT DBUSR FROM ENVIRONMENT-VALUE.
           DISPLAY "DATASRC_PWD" UPON ENVIRONMENT-NAME.
           ACCEPT DBPWD FROM ENVIRONMENT-VALUE.

           EXEC SQL WHENEVER SQLERROR GO TO 999-PRG-ERR END-EXEC.

           MOVE 'CONN1' TO DBS.

           MOVE 'CONNECT' TO CUR-STEP.
           EXEC SQL
             CONNECT :DBUSR
                     IDENTIFIED BY :DBPWD
                     AT            :DBS
                     USING         :DATASRC
           END-EXEC.

           MOVE 'START TRANSACTION' TO CUR-STEP.
           EXEC SQL AT :DBS
              START TRANSACTION
           END-EXEC.        
           
           MOVE 'DROP TABLE' TO CUR-STEP.
           EXEC SQL AT :DBS
                DROP TABLE IF EXISTS TAB00
           END-EXEC.

           MOVE 'CREATE TABLE' TO CUR-STEP.
           EXEC SQL AT :DBS
                CREATE TABLE TAB00 (VAR INT)
           END-EXEC.

           MOVE 1 TO IDX

           PERFORM UNTIL IDX > 10 OR SQLCODE < 0 OR SQLCODE = 100
               MOVE 'INSERT' TO CUR-STEP
               MOVE IDX TO VAR-TMP
               EXEC SQL AT :DBS
                   INSERT INTO TAB00 (VAR)
                       VALUES (:VAR-TMP)
               END-EXEC

               ADD 1 TO IDX
           END-PERFORM.

      * VM1 : CURSOR FROM FIELD CONTENT (EVALUATED AT OPEN)

           MOVE 'SELECT MAX(VAR) FROM TAB00' TO SQLCOMMAND-ARR
           MOVE FUNCTION LENGTH (FUNCTION TRIM (SQLCOMMAND-ARR))
             TO SQLCOMMAND-LEN
      
           MOVE 'OPEN-VM1' TO CUR-STEP. 
           EXEC SQL AT :DBS
               OPEN VM1 
           END-EXEC.
          
           EXEC SQL AT :DBS
               FETCH VM1 
               INTO
                 :VAR-RES
           END-EXEC.
           DISPLAY 'VM1 - VAR-RES:' VAR-RES.
          
           EXEC SQL AT :DBS
               CLOSE VM1 
           END-EXEC.

      * VM2 : CURSOR FROM PREPARED STATEMENT (FROM FIELD, EVAL. AT OPEN)

           MOVE 'SELECT MIN(VAR) FROM TAB00' TO SQLCOMMAND-ARR
           MOVE FUNCTION LENGTH (FUNCTION TRIM (SQLCOMMAND-ARR))
             TO SQLCOMMAND-LEN

           MOVE 'PREPARE-VM2' TO CUR-STEP. 
           EXEC SQL AT :DBS
               PREPARE PREPSTMT1 FROM :SQLCOMMAND
           END-EXEC.

           MOVE 'OPEN-VM2' TO CUR-STEP. 
           EXEC SQL AT :DBS
               OPEN VM2 
           END-EXEC.
          
           EXEC SQL AT :DBS
               FETCH VM2
               INTO
                 :VAR-RES
           END-EXEC.
           DISPLAY 'VM2 - VAR-RES:' VAR-RES.
          
           EXEC SQL AT :DBS
               CLOSE VM2 
           END-EXEC.

      * VM3 : CURSOR FROM DIRECT STATEMENT (EVAL. AT OPEN)

           MOVE 'OPEN-VM3' TO CUR-STEP. 
           EXEC SQL AT :DBS
               OPEN VM3 
           END-EXEC.
          
           EXEC SQL AT :DBS
               FETCH VM3
               INTO
                 :VAR-RES
           END-EXEC.
           DISPLAY 'VM3 - VAR-RES:' VAR-RES.
          
           EXEC SQL AT :DBS
               CLOSE VM3 
           END-EXEC.

      * DONE

           MOVE 'COMMIT' TO CUR-STEP.
           EXEC SQL AT :DBS
              COMMIT
           END-EXEC.        

           MOVE 'DISCONNECT' TO CUR-STEP.
           EXEC SQL
              CONNECT RESET :DBS
           END-EXEC.        

       200-EXIT.
           STOP RUN.

       999-PRG-ERR.
           DISPLAY 'ERR - ' CUR-STEP ' : ' SQLCODE.
           DISPLAY 'ERR - ' CUR-STEP ' : ' SQLERRMC(1:SQLERRML).
           MOVE -1 TO RETURN-CODE.

When compiled and run, this outputs:

    VM1 - VAR-RES:00000010
    VM2 - VAR-RES:00000001
    VM3 - VAR-RES:00000009

**Comment by GitMensch** [comment]
fixed (per release notes)
