### ISSUE TITLE
FR: allow mapping of "NoRecCode"

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#95]
citpgsql docs claim that

> Oracle SQLCODE for a NOT FOUND condition is 1403

and provides a preparser option to adjust that number.

gixsql has that currently hard-coded to 100- https://github.com/mridoni/gixsql/blob/081674b3c03e1b97b0a2edf854a152d765331bee/runtime/libgixsql/gixsql.cpp#L1253-L1254

It would be nice to be able to configure that to support migrations (code that checks for 1403 - or any other number).
I'm not sure that a preparser option is the best way (would be possible but then would need to be passed as option, likely to `GIXSQLStartSQL`). Providing a runtime variable that is read in only during startup and parsed to a numeric value once - then be used _looks_ like a "cover most cases" and quite easy, so maybe go with that (at least until a different request gets up)?

**Comment by GitMensch** [comment]
ping to be added to a milestone; something like `GIXSQL_NOREC_CODE` _looks_ easy, and would really help with conversions from citpgsql and _maybe_ procob, but I'm unsure if that is a a good or bad design (in theory it would be more reasonable to specify that at compile time, but that hard-coding is down in the inner circles of the runtime).

**Comment by mridoni** [comment]
This actually requires support both in the runtime (for obvious reasons) and in the preprocessor (to generate the `WHENEVER NOT FOUND` clauses correctly).

I implemented this and I am testing it, if all goes well it should be in v1.0.18

**Comment by GitMensch** [comment]
Tested the runtime part - works like a charm.
