### ISSUE TITLE
Cursors cannot be re-opened after close

### ISSUE THREAD

**Issue by mridoni** [mridoni/gixsql#98]
currently when a cursor is closed, it is not just marked as such, but its declaration is removed. Since there is no `UNDECLARE CURSOR`, at the time it seemed the logical thing to do, but in all evidence it is not, since it prevents one from re-opening the cursor after it has been closed.

The solution might be just marking it as closed and destroying only the resources (if any) allocated when it is was opened, so leaving it ready for being re-opened.

_Originally posted by @mridoni in https://github.com/mridoni/gixsql/issues/88#issuecomment-1198970631_

**Comment by mridoni** [comment]
This patch should solve it, I hope to be able to issue a (pre?)release in the middle of next week containing also the improved `EXEC SQL VAR` stuff (#21)

[issue98.patch.txt](https://github.com/mridoni/gixsql/files/9218641/issue98.patch.txt)

**Comment by GitMensch** [comment]
According to the release notes - solved. I suggest closing it.
